version: "3"

services:
  api:
    build: ./back-end
    volumes:
    - ./back-end/src:/usr/src/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    restart: on-failure
  front-end:
    build: ./front-end
    ports:
      - "3001:3001"
    depends_on:
      - api
    restart: on-failure
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  my-db:
